# Generated by Django 3.1.1 on 2020-09-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__email', 'last_name'], 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='taskboard',
            options={'ordering': ['name'], 'verbose_name_plural': 'Taskboard'},
        ),
        migrations.AddField(
            model_name='taskboard',
            name='name',
            field=models.CharField(default='Tabule', max_length=50, verbose_name='Name'),
        ),
    ]
