# Generated by Django 3.1.1 on 2020-09-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0002_auto_20200910_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('owner', 'Owner')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.profile')),
                ('taskboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.taskboard')),
            ],
            options={
                'ordering': ['profile__last_name'],
            },
        ),
    ]
