# Generated by Django 3.1.1 on 2020-09-13 14:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taskboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0003_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['profile__last_name'], 'verbose_name_plural': 'Membership'},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('deadline', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2020, 9, 13, 16, 8, 37, 529394))], verbose_name='Deadline')),
                ('stage', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('almost_finished', 'Almost finished'), ('done', 'Done')], max_length=16, verbose_name='Stage')),
                ('time_of_creation', models.DateTimeField(auto_now=True, verbose_name='Time of creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.profile')),
                ('taskboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.taskboard')),
            ],
            options={
                'verbose_name_plural': 'Task',
                'ordering': ['title', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=taskboard.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other')], default='image', help_text='Select allowed attachment type', max_length=5, verbose_name='Attachment type')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.task')),
            ],
            options={
                'verbose_name_plural': 'Attachment',
            },
        ),
    ]
