# Generated by Django 3.1.1 on 2020-09-13 15:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0004_auto_20200913_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 9, 13))], verbose_name='Deadline'),
        ),
    ]
