# Generated by Django 3.1.1 on 2020-09-15 17:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0005_auto_20200913_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 9, 15))], verbose_name='Deadline'),
        ),
    ]
