# Generated by Django 3.1.1 on 2020-09-16 18:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0006_auto_20200915_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 9, 16))], verbose_name='Deadline'),
        ),
    ]
