# Generated by Django 3.1.1 on 2020-09-26 15:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0007_auto_20200916_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 9, 26))], verbose_name='Deadline'),
        ),
    ]
