# Generated by Django 3.1.1 on 2020-09-28 16:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0008_auto_20200926_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 9, 28))], verbose_name='Deadline'),
        ),
    ]
