# Generated by Django 3.1.1 on 2020-10-06 16:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0010_auto_20201003_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 10, 6))], verbose_name='Deadline'),
        ),
    ]
