# Generated by Django 3.1.1 on 2020-11-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0012_auto_20201104_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=150, null=True, verbose_name='Bio'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Text')),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.task')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
    ]
