# Generated by Django 3.1.1 on 2020-11-12 14:00

import constrainedfilefield.fields.file
import constrainedfilefield.fields.image
import datetime
import django.core.validators
from django.db import migrations, models
import taskboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0013_auto_20201104_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/jpg', 'image/bmp', 'image/gif', 'audio/aac', 'audio/mpeg', 'audio/ogg', 'audio/x-flac', 'audio/x-wav', 'video/mp4', 'video/x-ms-wmv', 'video/webm', 'application/pdf', 'text/plain', 'application/zip'], max_upload_size=52428800, mime_lookup_length=4096, null=True, upload_to=taskboard.models.attachment_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to=taskboard.models.profile_pic_path, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 12))], verbose_name='Deadline'),
        ),
    ]
