# Generated by Django 3.1.1 on 2020-11-13 17:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0014_auto_20201112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 13))], verbose_name='Deadline'),
        ),
    ]
