# Generated by Django 3.1.1 on 2020-11-14 19:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0015_auto_20201113_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 14))], verbose_name='Deadline'),
        ),
    ]
