# Generated by Django 3.1.1 on 2020-11-17 16:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0017_auto_20201115_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 17))], verbose_name='Deadline'),
        ),
    ]
