# Generated by Django 3.1.1 on 2020-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0018_auto_20201117_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bio'),
        ),
    ]
