# Generated by Django 3.1.1 on 2020-11-18 11:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0019_auto_20201117_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 18))], verbose_name='Deadline'),
        ),
    ]
