# Generated by Django 3.1.1 on 2020-11-19 22:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0020_auto_20201118_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 19))], verbose_name='Deadline'),
        ),
    ]
