# Generated by Django 3.1.1 on 2020-11-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0021_auto_20201119_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskboard.task'),
        ),
    ]
