# Generated by Django 3.1.1 on 2020-11-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0023_auto_20201124_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name_plural': 'Log'},
        ),
        migrations.AddField(
            model_name='log',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskboard.comment'),
        ),
        migrations.AddField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskboard.profile'),
        ),
    ]
