# Generated by Django 3.1.1 on 2020-11-29 14:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0024_auto_20201124_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 29))], verbose_name='Deadline'),
        ),
    ]
