# Generated by Django 3.1.1 on 2020-11-30 19:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0025_auto_20201129_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 11, 30))], verbose_name='Deadline'),
        ),
    ]
