# Generated by Django 3.1.1 on 2020-12-01 19:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0026_auto_20201130_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 12, 1))], verbose_name='Deadline'),
        ),
    ]
