# Generated by Django 3.1.1 on 2020-12-06 15:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0028_auto_20201203_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 12, 6))], verbose_name='Deadline'),
        ),
    ]
