# Generated by Django 3.1.1 on 2020-12-08 14:57

import constrainedfilefield.fields.file
import datetime
import django.core.validators
from django.db import migrations, models
import taskboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0030_auto_20201207_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['image/png', 'image/jpeg', 'image/bmp', 'image/gif', 'audio/aac', 'audio/mpeg', 'audio/ogg', 'audio/x-flac', 'audio/x-wav', 'video/mp4', 'video/x-ms-wmv', 'video/webm', 'application/pdf', 'text/plain', 'application/zip'], max_upload_size=52428800, mime_lookup_length=4096, null=True, upload_to=taskboard.models.attachment_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 12, 8))], verbose_name='Deadline'),
        ),
    ]
