# Generated by Django 3.1.1 on 2020-12-15 15:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0032_auto_20201213_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2020, 12, 15))], verbose_name='Deadline'),
        ),
    ]
