# Generated by Django 3.1.1 on 2021-01-04 17:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0038_auto_20201227_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 4))], verbose_name='Deadline'),
        ),
    ]
