# Generated by Django 3.1.1 on 2021-01-06 17:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0039_auto_20210104_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 6))], verbose_name='Deadline'),
        ),
    ]
