# Generated by Django 3.1.1 on 2021-01-09 14:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0042_auto_20210108_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 9))], verbose_name='Deadline'),
        ),
    ]
