version: '3'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rest_api


  web:
    container_name: backend
    build: backend
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: /entrypoint.sh

  client:
    container_name: frontend
    stdin_open: true
    build: frontend
    command: npm start 0.0.0.0:3000
    ports:
      - "3000:3000"



volumes:
  postgres_data:
