version: '3'

services:
  web:
    container_name: backend
    build: backend
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"

  client:
    stdin_open: true
    build: frontend
    command: npm start 0.0.0.0:3000
    ports:
      - "3000:3000"
