#Tento soubor umožňuje rozjet všechny 3 kontejnery bez toho, aby se do terminálu (nebo cmd) zadávaly dlouhé příkazy.
version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300


  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rest_api


  web:
    container_name: backend
    build: backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: /entrypoint.sh

  client:
    container_name: frontend
    stdin_open: true
    build: frontend
    command: npm start 0.0.0.0:3000
    ports:
      - "3000:3000"


#Tohle je důležité, protože bez toho by se po vypnutí databázového kontejneru veškerá data smazala.
volumes:
  postgres_data:
  elasticsearch-data:
      driver: local